spring:
    jpa:
        hibernate.ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        url: jdbc:h2:mem:minisys-db
        driver-class-name: org.h2.Driver
        username: sa
        password: sa
    h2:
        console:
            enabled: true
            path: /h2-console